@startuml name "finta"

class MatchResult {
  - id: unsigned long int
  - {static} nextId: unsigned long int
  - scoreHome: uint_8
  - scoreAway: uint_8

  + MatchResult(team1: Team, team2: Team, score1: uint_8, score2: uint_8)
  + getMatchResult(): string
  + setMatchResult(teamHome: Team, teamAway: Team, scoreHome: uint_8, scoreAway: uint_8): void
}

class Team {
  - name: string
  
  + Team(name: string)
  + getName(): string
  + setName(name: string): void
}

MatchResult "0..*" -- "teamHome 1" Team
MatchResult "0..*" -- "1 teamAway" Team 

@enduml
